### ISSUE TITLE
discuss: key vs object references

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#12]
The source schema for pxf uses key-based referencing extensively, particularly for entities. This has numerous advantages in the JSON. Entities can be sent over the wire independent of associations. Entities can live in separate files (VCF, ped, etc) and separate databases and referenced by ID. We avoid duplicating the same object tree multiple times.

Should the reference object model follow this slavishly? In theory we could replace the key reference to entity in Association with an object (if we are to automatically map to the JSON we would need some jackson trickery here).

My preference is to have the POJOs slavishly follow the structure of the JSON. This does not preclude either a convenience layer for looking up entities by key, neither does it preclude a distinct object model separate from the data access objects.

**Comment by julesjacobsen** [comment]
I'll try this approach - the object reference approach didn't work well using automatic mappings as the entity data were always required for de-serialization and written for serialization. Hopefully purely using String ids should work.

**Comment by julesjacobsen** [comment]
I think we've got the right balance now -  we're using object references for everything apart from references to Entities in an Association. These are referenced by id, which prevents a lot of duplication, and allows easy linking to external resources if the id is a URI/curie.

**Comment by cmungall** [comment]
Note to self: need to explain this on the wiki too
