### ISSUE TITLE
Decide on unit testing pattern

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#14]
Uses builders, e.g. #7 

and/or do this based on yaml/json files checked into src/test/resources

Note this means we may have two sets of examples - some in the format repo, and some here for testing. These could in theory be reused or synced but I don't think this is a major concern.

@julesjacobsen @hdietze and @jnguyenx to advise

**Comment by julesjacobsen** [comment]
Having actual examples to test on in src/test/resources is invaluable for making sure things work quickly and easily using a unit testing framework. They might be more functional integration tests, but whatever, it means we have complete end-to-end examples and have better assurance that the code can read and write the data as well has document/test the API directly.
