### ISSUE TITLE
Create a phenotools command line script

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#26]
analogous to http://vcftools.sourceforge.net/

operations include:

 * concat/merge
 * compare
 * convert
 * summarize
 * ...

we can imagine a number of commands that would be useful for data management - for example, to update ontology classes that have become obsoleted. Perhaps best done as a separate tool? Would this be useful to you @drseb?

**Comment by balhoff** [comment]
This is being developed here: https://github.com/phenopackets/pxftools
