### ISSUE TITLE
OntologyClass - should encapsulate frequency?

### ISSUE THREAD

**Issue by julesjacobsen** [phenopackets/phenopacket-reference-implementation#38]
Particularly for rare disease there are variations in presentation of particular phenotypes some are mandatory for a particular condition to be diagnosed, others are less well defined. Perhaps this is best contained in the Disease rather than on the OntologyClass.

**Comment by cmungall** [comment]
I was sure we had frequency and penetrance under phenotype...

**Comment by cmungall** [comment]
This can be modeled using some combination of an ontology class, and a quantity. For the former, we don't have any vocab in HPO (current annotations use strings)

For quantities, this is sometimes expressed as ratios, sometimes as percentages. Do we want fields for both?

**Comment by cmungall** [comment]
I believe this is now fixed by #41
