### ISSUE TITLE
Correct example on the README

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#42]
This isn't semantically correct

```
Disease disease = new Disease();
disease.setId("OMIM:101600");
disease.setLabel("Pfeiffer syndrome");
List<OntologyClass> phenotypes = ImmutableList.of(
        OntologyClass.of("HP:0000272", "Malar flattening"),
        OntologyClass.of("HP:0005347", "Cartilaginous trachea"),
        OntologyClass.of("HP:0001249", "Intellectual disability"),
        OntologyClass.of("HP:0005048", "Synostosis of carpal bones"),
        OntologyClass.of("HP:0004440", "Coronal craniosynostosis"),
        OntologyClass.of("HP:0001156", "Brachydactyly syndrome")
);
disease.setTypes(phenotypes);
```

here we are saying the disease occurrence is an instance of all these phenotypes. Really the disease occurrence is an instance of a disease (possibly at a stage, etc), and is linked to multiple phenotypes via phenotype-associations

**Comment by julesjacobsen** [comment]
This was my understanding of the ```phenotypes``` field - it is a set of phenotypes which are/can present as a result of a disease. i.e. the phenotypes themselves aren't the disease, they are the measureable obserations as a result of a disease occurrence.  How were you going to change the way this is represented?

**Comment by cmungall** [comment]
We would make a series of phenotype associations, with the disease as entity
