### ISSUE TITLE
Experiment: generate protobuf from model

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#6]
Use: https://github.com/FasterXML/jackson-dataformat-protobuf

**Comment by cmungall** [comment]
@jnguyenx can you help me out with this one?

**Comment by jnguyenx** [comment]
Sure I'll have a look this week.

**Comment by cmungall** [comment]
Now using this for https://github.com/phenopackets/phenopacket-format/issues/49
